extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../bril/benchmarks/**/*.bril'
# benchmarks = './test/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.myopt]
pipeline = [
    "bril2json",
    "./target/release/lvn -f",
    "brili -p {args}",
]
